/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package part2.java;

import org.testng.annotations.*;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.List;

import static org.testng.Assert.*;

public class AppTest {
    @Test public void testPart2LowestLocationWithSampleInput() throws IOException {
        Path filePath = Paths.get("../../tests/input.txt");
        List<String> fileReadLines = Files.readAllLines(filePath);
        String[] lines = fileReadLines.toArray(new String[0]);


        App classUnderTest = new App();
        assertEquals(classUnderTest.part2LowestLocation(lines), 46);
    }

    @Test public void testPart2LowestLocationWithRealInput() throws IOException {
        Path filePath = Paths.get("../../input.txt");
        List<String> fileReadLines = Files.readAllLines(filePath);
        String[] lines = fileReadLines.toArray(new String[0]);


        App classUnderTest = new App();
        assertEquals(classUnderTest.part2LowestLocation(lines), 99751240);
    }
}
